### ISSUE TITLE
[@alitajs/native插件用法] @alitajs/native这个插件的配置方法是什么

### ISSUE THREAD

**Issue by zjyfantasy** [alitajs/alita#195]
我按照官方文档配置@alitajs/native插件，
`
import { defineConfig } from 'alita';

export default defineConfig({
  appType: 'cordova',
  mobileLayout: false,
  packageId: 'com.biad.parkgame',
  displayName: 'biad.parkgame',
  plugins: ['@alitajs/native'],
  native: ['device'],
});
`

然后执行alita dev时报错

`cordova platform use android
cordova serve(pid:6268)
Invalid config key: native
Error: Invalid config key: native
    at Config.getConfig (D:\projects\biad.park.game.mobile\node_modules\@umijs\core\lib\Config\Config.js:178:13)
    at D:\projects\biad.park.game.mobile\node_modules\@umijs\core\lib\Service\Service.js:279:44
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\projects\biad.park.game.mobile\node_modules\@umijs\core\lib\Service\Service.js:108:103)
    at _next (D:\projects\biad.park.game.mobile\node_modules\@umijs\core\lib\Service\Service.js:110:194)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

我想知道原生能力像camera之类的该怎么配置，万分感谢

![image](https://user-images.githubusercontent.com/22555643/124906308-8380e980-e019-11eb-9180-96a7ccfbc0f6.png)

**Comment by xiaohuoni** [comment]
不是这个插件，是`@alitajs/cordova-native` 配置 `cordovanative`。native 有别的用途。文档不确定有没有更正了。这个功能 `cordovanative`，没在很多项目中运行过哦

**Comment by zjyfantasy** [comment]
@xiaohuoni 感谢，这个问题已经解决了，不过没有配置插件，是直接安装完插件直接调用的方式访问的，比如装完cordova-plugin-device然后在页面中以device.uuid访问是没问题的，不知道这种方式是否推荐

**Comment by xiaohuoni** [comment]
可以的，都是这么用的，这个插件我们也用的很少。本来是想像 ionic 那样做一个配置集合的。后面发现用的不多，就暂且搁置了，umi@4 之后，会完善 alita@3 的一些东西，会来做这个事情。
